//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOTVETINAVOPROSII
{
    using System;
    using System.Collections.Generic;
    
    public partial class Загадки_и_ответы
    {
        public int Код { get; set; }
        public Nullable<int> Код_тематики { get; set; }
        public string Загадка { get; set; }
        public string Ответ_1 { get; set; }
        public string Ответ_2 { get; set; }
        public string Ответ_3 { get; set; }
        public string Правильный_ответ { get; set; }
    
        public virtual Тематика_загадок Тематика_загадок { get; set; }
    }
}
