//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOTVETINAVOPROSII
{
    using System;
    using System.Collections.Generic;
    
    public partial class Результаты
    {
        public int Код { get; set; }
        public Nullable<int> Код_пользователя { get; set; }
        public Nullable<int> Кол_во_верных_ответов { get; set; }
        public Nullable<int> Код_тематики_вопросов { get; set; }
        public Nullable<int> Всего_вопросов_было { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Тематика_загадок Тематика_загадок { get; set; }
    }
}
